"""add notebook_sessions table

Revision ID: 1b4d4edb3c31
Revises: f19903bc4dd0
Create Date: 2026-02-10 19:58:30.997735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4d4edb3c31'
down_revision: Union[str, Sequence[str], None] = 'f19903bc4dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_sessions_notebook_id'), 'notebook_sessions', ['notebook_id'], unique=False)
    op.create_index(op.f('ix_notebook_sessions_session_id'), 'notebook_sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebook_sessions_session_id'), table_name='notebook_sessions')
    op.drop_index(op.f('ix_notebook_sessions_notebook_id'), table_name='notebook_sessions')
    op.drop_table('notebook_sessions')
    # ### end Alembic commands ###
